In [1]:
import numpy as np
import scipy as sp

In [66]:
# User-item matrix: 2 users, 3 items
R = np.array([[20, 5, 1],
              [0, 12, 0]]) 
#,[4,0,1]

In [67]:
U, S, Vt = np.linalg.svd(R, full_matrices=True, compute_uv=True)

It makes sense to show rounded values

In [68]:
np.round(U,1)

array([[ 1. , -0.2],
       [ 0.2,  1. ]])

U is orthonormal:

In [82]:
np.round(np.multiply(U,U.T),1)

array([[ 1., -0.],
       [-0.,  1.]])

In [83]:
S

array([20.93406586, 11.47888873])

Pad sigma matrix with a column of zeros to get (2,3) shape

In [88]:
Sigma = np.hstack((np.multiply(S, np.eye(2)),[[0],[0]]))
np.round(Sigma,1)

array([[20.9,  0. ,  0. ],
       [ 0. , 11.5,  0. ]])

Vt

In [86]:
np.round(Vt,1)

array([[ 0.9,  0.3,  0. ],
       [-0.3,  0.9, -0. ],
       [-0. ,  0. ,  1. ]])

In [89]:
X = np.dot(Sigma,Vt)
np.round(X,1)

array([[19.6,  7.3,  1. ],
       [-4. , 10.8, -0.2]])

In [90]:
np.round(np.dot(U, X),1)

array([[20.,  5.,  1.],
       [ 0., 12.,  0.]])

In [92]:
np.round(np.dot(U.T,R),1)

array([[19.6,  7.3,  1. ],
       [-4. , 10.8, -0.2]])